---
# tasks file for enable_cmsp
- name: Start task to enable CMSP
  uri:
    url: "https://{{nutanix_host}}:{{nutanix_port}}/api/nutanix/v3/prism_central/cmsp/configure"
    body:
      operation: "kEnable"
      config:
        platform_network_configuration:
          subnet_mask: "{{ cmsp_subnet_mask }}"
          type: "{{ cmsp_network_type }}"
          default_gateway: "{{ cmsp_network_default_gateway }}"
        pc_domain_name: "{{ cmsp_domain_name }}"
        platform_ip_block_list: "{{ cmsp_platform_ip_block_list }}"
    method: POST
    validate_certs: "{{ validate_certs }}"
    body_format: json
    status_code: 202
    headers:
      Authorization: "{{ nutanix_api_auth }}"
  register: nutanix_cmsp_enable_result

- name: Debug nutanix_cmsp_enable_result
  debug:
    var: nutanix_cmsp_enable_result.json
  when:
    - nutanix_debug

- name: Wait for CMSP enable task to complete
  block:
    - name: Checking CMSP enable task status
      uri:
        url: "https://{{nutanix_host}}:{{nutanix_port}}/PrismGateway/services/rest/v2.0/tasks/{{ nutanix_cmsp_enable_result.json.task_uuid }}"
        method: GET
        validate_certs: "{{ validate_certs }}"
        status_code: 200
        headers:
          Authorization: "{{ nutanix_api_auth }}"
      register: prism_cmsp_enable_task_status
      until: prism_cmsp_enable_task_status.json.progress_status == 'Succeeded' or prism_cmsp_enable_task_status.json.progress_status == 'Failed'
      retries: 30
      delay: 120

- name: Debug prism_cmsp_enable_task_status
  debug:
    var: prism_cmsp_enable_task_status
  when:
    - nutanix_debug

- name: Checking CMSP enable task failed
  ansible.builtin.fail:
    msg: "CMSP enable task failed. {{ prism_cmsp_enable_task_status.json.message }}"
  when:
    - prism_cmsp_enable_task_status.json.progress_status == 'Failed'
