---
# tasks file for enable_cmsp
- debug:
    var: nutanix_host

- debug:
    var: nutanix_port

- name: Start task to validate that CMSP can be enabled
  uri:
    url: "https://{{ nutanix_host }}:{{ nutanix_port }}/api/nutanix/v3/prism_central/cmsp/configure"
    body:
      operation: "kValidate"
      config:
        platform_network_configuration:
          subnet_mask: "{{ cmsp_subnet_mask }}"
          type: "{{ cmsp_network_type }}"
          default_gateway: "{{ cmsp_network_default_gateway }}"
        pc_domain_name: "{{ cmsp_domain_name }}"
        platform_ip_block_list: "{{ cmsp_platform_ip_block_list }}"
    method: POST
    validate_certs: "{{ validate_certs }}"
    body_format: json
    status_code: 202
    headers:
      Authorization: "{{ nutanix_api_auth }}"
  register: nutanix_cmsp_validation_result

- name: Debug nutanix_cmsp_validation_result
  debug:
    var: nutanix_cmsp_validation_result.json
  when:
    - nutanix_debug

- name: Wait for CMSP validatation task to complete
  ansible.builtin.import_role:
    name: grdavies.nutanix_role_prism_monitor_task
  vars:
    nutanix_task_uuid: "{{ nutanix_cmsp_validation_result.json.task_uuid }}"
    nutanix_task_retries: 10
    nutanix_task_retry_delay: 5

- name: Set prism_cmsp_validate_task_status
  set_fact:
    prism_cmsp_validate_task_status: "{{ monitored_task }}"

- name: Debug prism_cmsp_validate_task_status.json
  debug:
    var: prism_cmsp_validate_task_status.json
  when:
    - nutanix_debug
